18 create cohorts page
GSG-G13/code-academy pull request #22
Opened 2023-06-26 11:34 UTC by KhaledAref13

2023-06-27 09:54 UTC, Nour-Agha99 approved these changes

2023-06-27 10:37 UTC, Batrawi approved these changes

2023-06-27 11:17 UTC, karamzomlot requested changes
Delete any empty `style.ts` files  (`/src/components/Cohorts/CohortsWrapper/style.ts`, `/src/components/Cohorts/CohortMembersTopBar/style.ts`)

2023-06-27 11:17 UTC, karamzomlot commented on src/components/Cohorts/CohortCard/index.tsx
> +      <CohortCardImgDiv>
Could you make this component when you click it on redirect you to the cohort page?
hint (useNavigate hook from `react-router-dom`)

2023-06-27 11:17 UTC, karamzomlot commented on src/components/Cohorts/CohortCard/style.ts
> +    border-bottom-color: #0abb87;
I think the hover will be better without the bottom border Coz we have a button (visit)

2023-06-27 11:17 UTC, karamzomlot commented on src/components/Cohorts/CohortCard/style.ts
> +  padding: 4px;
Increasing the padding will be better e.g.: (`padding: .6rem 1rem;`)

2023-06-27 11:17 UTC, karamzomlot commented on src/components/Cohorts/CohortCard/style.ts
> +  background: url('../../../public/cohort-background.jpg') center center;
When you have any file in the public folder you can access it with an absolute  path like this (`/public/file.jpg`).

One more thing if you can change the image to any image from `GSG` will be more beautiful. I will leave to you edited style for this component with adding glass effect

```tsx
const CohortCardImgDiv = styled('div')`
  width: 100%;
  height: 150px;
  background: url('https://mlwhex1ecbob.i.optimole.com/w:1814/h:1102/q:mauto/f:avif/https://gazaskygeeks.com/wp-content/uploads/2020/08/Copy-of-GAT1038.jpg') center center;
  background-repeat: no-repeat;
  background-size: cover;
  border-top-right-radius: 0.3rem;
  border-top-left-radius: 0.3rem;
  display: flex;
  justify-content: center;
  align-items: center;
  cursor: pointer;
  position: relative;

  &::after {
    content: '';
    position: absolute;
    width: 100%;
    height: 100%;
    background-color: #4a4a4a8c;
    backdrop-filter: blur(5px);
    border-top-right-radius: 0.3rem;
    border-top-left-radius: 0.3rem;
  }
`;
```
But Coz I used position absolute and relative you should edit the avatar style with adding `z-index: 1`.

```tsx
<Avatar
  alt={alt}
  src={imgSrc}
  sx={{
  width: 90, height: 90, boxShadow: '0 0 0 5px #ffffff', zIndex: 1,
  }}
/>
```

2023-06-27 11:17 UTC, karamzomlot commented on src/components/Cohorts/CohortsTopBar/LoadingButton.tsx
> +        onClick={handleClick}
It's not best practice to disable eslint in your case you can use this 
```tsx
onClick={() => handleClick()}
```

2023-06-27 11:17 UTC, karamzomlot commented on src/components/Cohorts/CohortsTopBar/LoadingButton.tsx
> +        startIcon={<FaUserFriends />}
To make the component reusable you can add the `startIcon` as a prop and use the button on all pages by adding the text and the icon, other props

2023-06-27 11:17 UTC, karamzomlot commented on src/pages/user/Cohorts.tsx
> +  padding: calc(70px + 1rem) 1rem 1rem;
Keep this padding in the outlet,

`layout.tsx`
```tsx
const OutletContainer = styled.div`
  width: 100%;
  padding-top: calc(70px);
`;
```

`Cohorts.tsx`
```tsx
const CohortsContainer = styled.div`
  padding: 1rem 1rem;
`;
```

2023-06-27 11:17 UTC, karamzomlot commented on src/pages/user/indext.ts
> +export default Cohorts;
Why do you have 2 index files in the same folder
hint this file is `indext.ts` not `index.ts`

and you have an `index.ts` file so you can delete this file and use another one

2023-06-27 11:17 UTC, karamzomlot commented on src/router/index.tsx
> +      { path: 'cohorts', element: <Cohorts /> },
Add single cohort page route
```tsx
{ path: 'cohorts', element: <Cohorts /> },
{ path: 'cohorts/:cohortName', element: <div>Single Cohort</div> },
```

2023-06-29 12:29 UTC, Shatha-Amin approved these changes

2023-07-02 05:31 UTC, Batrawi approved these changes

2023-07-04 08:46 UTC, karamzomlot approved these changes

2023-07-04 08:46 UTC, karamzomlot commented on src/components/Cohorts/CohortsTopBar/LoadingButton.tsx
> +          'border-color': 'rgba(0,0,0,0)',
borderColor not 'border-color` 
If you open the browser console you will notice this error

2023-07-04 08:46 UTC, karamzomlot commented on src/components/Cohorts/CohortCard/index.tsx
> +      <CohortCardImgDiv>
@KhaledAref13 
Here I mean `CohortCardImgDiv` when clicking on redirects you to the single cohort

2023-07-04 08:46 UTC, karamzomlot commented on src/components/Cohorts/CohortsTopBar/LoadingButton.tsx
> +        onClick={handleClick}
@KhaledAref13 
You edit this but forget to delete the comment (disable eslint)

2023-07-04 08:46 UTC, karamzomlot commented on src/components/Cohorts/CohortsTopBar/LoadingButton.tsx
> +          'border-color': 'rgba(0,0,0,0)',
@KhaledAref13 
Nothing is updated here.

2023-07-04 08:46 UTC, merged