23 create auth provider
GSG-G13/code-academy pull request #24
Opened 2023-06-29 12:16 UTC by Nour-Agha99

2023-06-29 12:28 UTC, Shatha-Amin approved these changes

2023-07-01 21:01 UTC, KhaledAref13 approved these changes

2023-07-02 05:30 UTC, Batrawi approved these changes

2023-07-02 12:07 UTC, karamzomlot requested changes

2023-07-02 12:07 UTC, karamzomlot commented on src/App.tsx
> +import MyRouter from './router';
Why you rename it?

2023-07-02 12:07 UTC, karamzomlot commented on src/contexts/AuthContext.tsx
> +const RequireAuthProvider: React.FC<AuthProviderPropsType> = ({ children }) => {
You can add the props type like this:
```tsx
const RequireAuthProvider = ({ children }: AuthProviderPropsType) => {...}
```

2023-07-02 12:07 UTC, karamzomlot commented on src/contexts/AuthContext.tsx
> +    return <div>Loading...</div>;
Good job man🔥
But here if you can create a loading page it will be perfect instead of this div

2023-07-02 12:07 UTC, karamzomlot commented on src/utils/helpers/LoggedUserObjectType.ts
> +  userEmail: string | null;
Why add null for each prop?
I think there is no need for this

2023-07-02 12:07 UTC, karamzomlot commented on src/hooks/useAuth.ts
> +  });
You can initialize the state without adding the value and add it to the state when the user exists.

This will make it easy to check the user in the `AuthContext` like this:
``` ts
if (!user) // do anything
```

2023-07-02 12:07 UTC, karamzomlot commented on src/contexts/AuthContext.tsx
> +  );
You can do it like this (using `useNavigate` hook it's better than using `Navigate` component:

```tsx
const navigate = useNavigate(); // from react-router-dom

if (!user) {
  navigate('/academy/login');
  return null;
}

return (
   children
);
```

2023-07-02 18:30 UTC, merged